name: Autograding Tests
'on':
- push
- repository_dispatch
permissions:
  checks: write
  actions: read
  contents: read
jobs:
  run-autograding-tests:
    runs-on: ubuntu-latest
    if: github.actor != 'github-classroom[bot]'
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    - name: Run_test
      id: run_test
      uses: classroom-resources/autograding-python-grader@v1
      with:
        timeout: 10
        setup-command: run_test.py 
    - name: Autograding Reporter
      uses: classroom-resources/autograding-grading-reporter@v1
      env:
        RUN_TEST_RESULTS: "${{steps.run_test.outputs.result}}"
      with:
        runners: run_test
