name: Autograding Tests
'on':
- push
- repository_dispatch
permissions:
  checks: write
  actions: read
  contents: read
jobs:
  run-autograding-tests:
    runs-on: ubuntu-latest
    if: github.actor != 'github-classroom[bot]'
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    - name: Run_test
      id: run_test
      uses: classroom-resources/autograding-python-grader@v1
      with:
          # Command to install necessary libraries
          setup-command: 'pip install nbformat'
          # Command to run your test script
          run-command: 'python run_test.py'
          # Max points for this test
          points: 10
          # Timeout in minutes
          timeout: 5
    - name: Autograding Reporter
      uses: classroom-resources/autograding-grading-reporter@v1
      env:
        RUN_TEST_RESULTS: "${{steps.run_test.outputs.result}}"
      with:
        runners: run_test
